/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package visao;

import controle.ConexaoBD;

import controle.ControleEmpresa;
import modelo.ModeloEmpresa;
import modelo.ModeloTabela;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Gabriel Ferreira
 */
public class FormEditarEmpresa extends javax.swing.JFrame {
    
    ModeloEmpresa mod= new ModeloEmpresa();
    
    ControleEmpresa contro= new ControleEmpresa();
    ConexaoBD conex= new ConexaoBD();
     int flag= 0;
    

    public FormEditarEmpresa() {
        initComponents();
        
        //Vai exibir em ordem alfabetica de acordo com os nomes 
        preencherTabela("select *from empresa order by nome_empresa");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jFormattedTextFieldCNPJ = new javax.swing.JFormattedTextField();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEmpresa = new javax.swing.JTable();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jButtonPesquisa = new javax.swing.JButton();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Nome:");

        jLabel3.setText("CNPJ");

        jLabel4.setText("Senha:");

        jLabel5.setText("Email:");

        jFormattedTextFieldCNPJ.setEnabled(false);
        jFormattedTextFieldCNPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldCNPJActionPerformed(evt);
            }
        });

        jTextFieldNome.setEnabled(false);

        jTextFieldEmail.setEnabled(false);
        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jTableEmpresa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableEmpresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEmpresaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableEmpresa);

        jButtonPesquisa.setText("VALIDAR");
        jButtonPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaActionPerformed(evt);
            }
        });

        jPasswordFieldSenha.setEnabled(false);

        jLabel6.setText("Digite o CNPJ para permissão de edição/exclusão:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextFieldCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(jPasswordFieldSenha)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)))
                .addGap(53, 53, 53)
                .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jButtonPesquisa))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel6)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordFieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonExcluir))
                .addGap(124, 124, 124)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisa))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(301, 301, 301))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("EDIÇÃO DE EMPRESA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(816, 688));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaActionPerformed
        // vai insetar dentro de pesquisa o que a empresa digitou , no caso, o numero do cpf
        //mod.setPesquisa(jFormattedTextFieldCpf.getText());

    

       /* jTextFieldNome.setEnabled(false);
        jPasswordFieldSenha.setEnabled(false);
        jTextFieldEmail.setEnabled(false);
        jFormattedTextFieldCNPJ.setEnabled(false);*/
      

        mod.setPesquisa(jTextFieldPesquisa.getText());

        ModeloEmpresa model= contro.buscaEmpresa(mod);

        jFormattedTextFieldCNPJ.setText(model.getCnpj());
        jTextFieldNome.setText(model.getNome());
        jTextFieldEmail.setText(model.getEmail());
        jPasswordFieldSenha.setText(model.getSenha());
     


        if (jFormattedTextFieldCNPJ.getText().equals("")) {
             
         jTextFieldNome.setEnabled(!true);
         jFormattedTextFieldCNPJ.setEnabled(false);
         jPasswordFieldSenha.setEnabled(!true);
         jTextFieldEmail.setEnabled(!true);

         jButtonCancelar.setEnabled(true);

          

        jButtonSalvar.setEnabled(!true);
        jButtonExcluir.setEnabled(!true);
        
        }
        else{
            //Comando para mandar uma msg pra tela dizendo que o que o usuario digitou nao condiz com o que tem que digitar para entrar
          
            //liberando os botoes
        
         jTextFieldNome.setEnabled(true);
         jFormattedTextFieldCNPJ.setEnabled(false);
         jPasswordFieldSenha.setEnabled(true);
         jTextFieldEmail.setEnabled(true);

         jButtonCancelar.setEnabled(true);

          

        jButtonSalvar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
      
       
        }

    }//GEN-LAST:event_jButtonPesquisaActionPerformed

    private void jTableEmpresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEmpresaMouseClicked
        // TODO add your handling code here:

        //Preencher os campos em cima

        String emailEmpresa= ""+jTableEmpresa.getValueAt(jTableEmpresa.getSelectedRow(), 1);

        conex.conexao();

        conex.executaSql("select *from empresa where email_empresa = '"+emailEmpresa+"' ");

        try {
            conex.rs.first();
            jTextFieldEmail.setText(conex.rs.getString("email_empresa"));
            jFormattedTextFieldCNPJ.setText(conex.rs.getString("cnpj"));
            
            jPasswordFieldSenha.setText(conex.rs.getString("senha_empresa"));  
            jTextFieldNome.setText(conex.rs.getString("nome_empresa"));
           

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao selecionar os dados"+ex);
        }

        conex.desconecta();
     
        jButtonExcluir.setEnabled(true);

    }//GEN-LAST:event_jTableEmpresaMouseClicked

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
        int resposta=0;
        //Vai ser perguntado pra a empresa se ele quer excluir
        resposta=  JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir ?");
        //Se ele disser sim vai excluir
        if(resposta== JOptionPane.YES_OPTION){
            //mod.setCod_endereco(Integer.parseInt(jTextFieldCodEndereco.getText()));
            mod.setCnpj(jFormattedTextFieldCNPJ.getText());

            //mod.setMentor(Integer.parseInt(jFormattedTextFieldMentor.getText()));
            contro.Excluir(mod);
        }

        //DEpois de excluir os campos vão ficar em branco :
        jTextFieldNome.setText(" ");
        jTextFieldEmail.setText(" ");
        jPasswordFieldSenha.setText(" ");
        jFormattedTextFieldCNPJ.setText(" ");
        
        TelaLoginEmpresa tela= new TelaLoginEmpresa();
        tela.setVisible(true);
        dispose();
        
  

    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
       TelaLoginEmpresa tela = new TelaLoginEmpresa(); //Chama a tela de login empresa
        tela.setVisible(true);//
        dispose();

    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // TODO add your handling code here:

            mod.setCnpj(jFormattedTextFieldCNPJ.getText());
            mod.setNome(jTextFieldNome.getText());
            mod.setSenha(jPasswordFieldSenha.getText());
            mod.setEmail(jTextFieldEmail.getText());
          

            contro.Editar( mod);

       
          
          

            jTextFieldNome.setEnabled(false);
            jFormattedTextFieldCNPJ.setEnabled(false);
            jPasswordFieldSenha.setEnabled(false);
            jTextFieldEmail.setEnabled(false);

            jButtonCancelar.setEnabled(false);

          

            jButtonSalvar.setEnabled(false);

        

    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jFormattedTextFieldCNPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCNPJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldCNPJActionPerformed

    public void preencherTabela(String Sql){
        ArrayList dados= new ArrayList();
        String [] colunas= new String []{"CNPJ", "Email" ,  "Senha", "Nome"};
        
        conex.conexao();
        conex.executaSql(Sql);
        
        try {
            conex.rs.first();
            
            do{
                dados.add(new Object[]{conex.rs.getString("cnpj"),conex.rs.getString("email_empresa"), conex.rs.getString("senha_empresa"),conex.rs.getString("nome_empresa")});
                
            }while(conex.rs.next());
            
        } catch (SQLException ex) {
            
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher o ArrayList"+ex);
        }
        
        ModeloTabela modelo= new ModeloTabela(dados, colunas);
        
        jTableEmpresa.setModel(modelo);
        jTableEmpresa.getColumnModel().getColumn(0).setPreferredWidth(50);
        
        //Empresa nao vai poder mecher com o tamanho da tabela com o mause:
        jTableEmpresa.getColumnModel().getColumn(0).setResizable(false);
        
        jTableEmpresa.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTableEmpresa.getColumnModel().getColumn(1).setResizable(false);
        jTableEmpresa.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTableEmpresa.getColumnModel().getColumn(2).setResizable(false);
        jTableEmpresa.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTableEmpresa.getColumnModel().getColumn(3).setResizable(false);
     
      

        
        //Aqui o empresa nao vai poder reordenar o cabeçalho:
        jTableEmpresa.getTableHeader().setReorderingAllowed(false);
        
        //Empresa nao vai poder redimensionar a tabela:
        jTableEmpresa.setAutoResizeMode(jTableEmpresa.AUTO_RESIZE_OFF);
        
        //Empresa so vai poder selecionar um campo por vez ao clicar na tabela:
        jTableEmpresa.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
         
        
        
        
        conex.desconecta();
        
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormEditarEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormEditarEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormEditarEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormEditarEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormEditarEmpresa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonPesquisa;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JFormattedTextField jFormattedTextFieldCNPJ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEmpresa;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPesquisa;
    // End of variables declaration//GEN-END:variables
}
